volumes:
  pet:

services:
  getty:
    image: getty:latest
    container_name: getty
    restart: always
    volumes:
      - type: volume
        source: pet
        target: /pet
    ports:
      - "9999:9999"